import type { DocConfig } from "@/types/spj";

export const DEFAULT_DOC_CONFIG: DocConfig = {
  // ── IDENTITAS UMUM ──
  kopNamaPemerintah: "PEMERINTAH KOTA/KABUPATEN [NAMA DAERAH]",
  kopNamaSkpd: "DINAS PENDIDIKAN DAN KEBUDAYAAN",
  kopAlamat: "Jl. Pendidikan No. 1, Kec. Klojen",
  kopTelepon: "Telp. (0XX) XXXXXX  |  Email: admin@sekolah.sch.id",
  
  tahun: "2026",
  tempat: "Klojen",
  
  labelJabatanKiri: "Pejabat Pembuat Komitmen",
  kepala: "[Nama Kepala Sekolah]",
  nipKepala: "NIP. 19700101 200001 1 001",
  
  labelJabatanKanan: "Bendahara Pengeluaran",
  bendahara: "[Nama Bendahara]",
  nipBendahara: "NIP. 19800101 201001 2 002",
  nip: "NIP. 19800101 201001 2 002",

  // ── 1. KWITANSI ──
  kwtTitle: "KUITANSI",
  kwtLabelNo: "No.",
  kwtLabelTerimaDari: "Telah terima dari",
  kwtTerimaDari: "[Nama Instansi]",
  kwtLabelUangSejumlah: "Uang sejumlah",
  kwtLabelUntuk: "Untuk",
  kwtLabelTerbilang: "Terbilang",
  kwtTeksTerlampir: "(Bukti/Nota/Faktur terlampir)",
  kwtLabelSetuju: "Setuju dibayar,",
  kwtLabelLunas: "Lunas dibayar,",
  kwtLabelPenerima: "Penerima",
  namaSekolah: "SD Negeri XYZ",
  namaKepsek: "[Nama Kepala Sekolah]",
  tanggalKwitansi: "12 April 2026",
  tanggalLunas: "14 April 2026",

  // ── 2. TANDA BUKTI PEMBAYARAN (TBP) ──
  tbpTitle: "TANDA BUKTI PEMBAYARAN",
  tbpTahunAnggaran: "Tahun Anggaran: 2026",
  tbpMataAnggaran: "Mata Anggaran",
  tbpTerimaDari: "Sudah terima dari",
  tbpPihakPertama: "Kuasa Pengguna Anggaran",
  tbpUangSebesar: "Uang Sebesar",
  tbpTerbilang: "Terbilang:",
  tbpUntukPembayaran: "Untuk Pembayaran",
  tbpLunasTgl: "Lunas dibayar tanggal:",
  tbpPenerimaUang: "Penerima Uang",
  tanggalTbp: "26 Januari 2026",

  // ── 3. BERITA ACARA PEMBAYARAN (BAP) ──
  bapTitle: "BERITA ACARA PEMBAYARAN",
  bapNomor: "Nomor: 028/BAP/2026",
  bapPadaHariIni: "Pada hari ini, tanggal ......... bulan ......... tahun 2026, kami yang bertanda tangan di bawah ini:",
  bapPihakPertamaLabel: "PIHAK PERTAMA (Yang Membayar)",
  bapPihakKeduaLabel: "PIHAK KEDUA (Yang Menerima)",
  bapPihakKeduaNama: "[Nama Toko / Penerima]",
  bapPihakKeduaJabatan: "Pimpinan / Pemilik Usaha",
  bapTeksTengah: "PIHAK PERTAMA telah melakukan pembayaran dan PIHAK KEDUA telah menerima pembayaran yang sah dengan rincian sebagai berikut:",
  hBapNo: "No.",
  hBapUraian: "Uraian Pembayaran",
  hBapJumlah: "Jumlah (Rp)",
  bapTeksPenutup: "Demikian Berita Acara Pembayaran ini dibuat dalam rangkap yang secukupnya untuk dipergunakan sebagaimana mestinya dan penuh tanggung jawab.",

  // ── 4. NOTA PESANAN (PO) ──
  poTitle: "NOTA PESANAN",
  poNomor: "Nomor: 027/PO/2026",
  poKepadaLabel: "Kepada Yth.",
  poPenyedia: "[Nama Toko / Penyedia Barang]",
  poAlamatPenyedia: "Di Tempat",
  poTeksPembuka: "Harap disediakan barang/jasa di bawah ini sesuai dengan spesifikasi dan harga yang telah disepakati:",
  hPoNo: "No.",
  hPoNamaBarang: "Nama / Spesifikasi Barang",
  hPoQty: "Volume",
  hPoHargaSatuan: "Harga Satuan (Rp)",
  hPoTotal: "Total Harga (Rp)",
  poTeksPenutup: "Barang/jasa tersebut harap dikirimkan dalam keadaan baik dan lengkap ke alamat kantor kami selambat-lambatnya sesuai tanggal kesepakatan.",
  tanggalPo: "10 Januari 2026",

  // ── 5. BERITA ACARA SERAH TERIMA (BAST) ──
  bastTitle: "BERITA ACARA SERAH TERIMA BARANG",
  bastNomor: "Nomor: 029/BAST/2026",
  bastPadaHariIni: "Pada hari ini, tanggal ......... bulan ......... tahun 2026, kami yang bertanda tangan di bawah ini:",
  bastPihakPertamaLabel: "PIHAK PERTAMA (Yang Menyerahkan)",
  bastPihakPertamaNama: "[Nama Toko / Penyedia]",
  bastPihakPertamaJabatan: "Pimpinan / Pemilik Usaha",
  bastPihakKeduaLabel: "PIHAK KEDUA (Yang Menerima)",
  bastPihakKeduaNama: "[Nama Pejabat Penerima]",
  bastPihakKeduaJabatan: "Pejabat Pembuat Komitmen",
  bastTeksTengah: "PIHAK PERTAMA telah menyerahkan hasil pekerjaan/barang dan PIHAK KEDUA telah menerima hasil pekerjaan/barang dalam keadaan baik dan cukup dengan rincian sebagai berikut:",
  hBastNo: "No.",
  hBastNamaBarang: "Nama / Spesifikasi Barang",
  hBastQty: "Volume",
  hBastKeterangan: "Keterangan",
  bastTeksPenutup: "Demikian Berita Acara Serah Terima ini dibuat dalam rangkap yang secukupnya untuk dipergunakan sebagaimana mestinya.",

  // ── 6. BERITA ACARA PENERIMAAN BARANG (BAPB) ──
  bapbTitle: "BERITA ACARA PEMERIKSAAN DAN PENERIMAAN BARANG",
  bapbNomor: "Nomor: 030/BAPB/2026",
  bapbPadaHariIni: "Pada hari ini, tanggal ......... bulan ......... tahun 2026, kami yang bertanda tangan di bawah ini:",
  bapbPihakPertamaLabel: "PIHAK PERTAMA (Yang Menyerahkan)",
  bapbPihakPertamaNama: "[Nama Toko / Penyedia]",
  bapbPihakPertamaJabatan: "Pimpinan / Pemilik Usaha",
  bapbPihakKeduaLabel: "PIHAK KEDUA (Panitia / Penerima)",
  bapbPihakKeduaNama: "[Nama Panitia Penerima Barang]",
  bapbPihakKeduaJabatan: "Panitia Penerima Hasil Pekerjaan",
  bapbTeksTengah: "Berdasarkan Nota Pesanan, PIHAK KEDUA telah melakukan pemeriksaan fisik terhadap barang yang dikirimkan oleh PIHAK PERTAMA. Hasil pemeriksaan menunjukkan barang telah diterima dengan rincian dan kondisi sebagai berikut:",
  hBapbNo: "No.",
  hBapbNamaBarang: "Nama / Spesifikasi Barang",
  hBapbQty: "Volume",
  hBapbKondisi: "Kondisi Barang",
  bapbTeksPenutup: "Demikian Berita Acara Penerimaan Barang ini dibuat dengan sebenarnya untuk dapat dipergunakan sebagaimana mestinya.",

  // ── 7. PENAWARAN HARGA (PH) ──
  phTitle: "SURAT PENAWARAN HARGA",
  phNomor: "Nomor: 015/SPH/2026",
  phTanggal: ".................... 2026",
  phPerihal: "Penawaran Harga Barang / Jasa",
  phKepadaLabel: "Kepada Yth.",
  phPenyedia: "[Nama Toko / Penyedia]",
  phAlamatPenyedia: "[Alamat Toko]",
  phTeksPembuka: "Dengan hormat,\nMemenuhi permintaan penawaran harga dari instansi Bapak/Ibu, bersama ini kami sampaikan penawaran harga barang/jasa dengan rincian sebagai berikut:",
  hPhNo: "No.",
  hPhNamaBarang: "Nama/Spesifikasi Barang",
  hPhQty: "Volume",
  hPhHargaSatuan: "Harga Satuan (Rp)",
  hPhTotal: "Total Harga (Rp)",
  phTeksPenutup: "Harga tersebut di atas sudah termasuk pajak dan biaya pengiriman. Demikian surat penawaran ini kami sampaikan, atas perhatian dan kerjasamanya kami ucapkan terima kasih.",

  // ── 8. FAKTUR / INVOICE ──
  fakturTitle: "FAKTUR PENJUALAN",
  fakturNomor: "INV/016/2026",
  fakturTanggal: ".................... 2026",
  fakturKepadaLabel: "Kepada Yth.",
  fakturPenyedia: "[Nama Toko / Penyedia]",
  fakturAlamatPenyedia: "[Alamat Toko]",
  hFakturNo: "No.",
  hFakturNamaBarang: "Nama Barang / Jasa",
  hFakturQty: "Qty",
  hFakturHargaSatuan: "Harga Satuan (Rp)",
  hFakturTotal: "Total Harga (Rp)",
  fakturTeksPenutup: "Pembayaran dapat ditransfer ke rekening toko kami. Terima kasih atas kepercayaan Anda.",
};  