export const REF_REKENING_ARKAS = [
  // ─── BELANJA PEGAWAI ───────────────────────────────────────────────────────
  { kode: "5.1.01.03.07.0002", nama: "Belanja Honorarium Pengadaan Barang/Jasa", kategori: "Belanja Pegawai" },
  { kode: "5.1.01.03.07.0013", nama: "Belanja Honorarium Bendahara", kategori: "Belanja Pegawai" },

  // ─── BELANJA BARANG ────────────────────────────────────────────────────────
  { kode: "5.1.02",            nama: "Belanja Barang dan Jasa", kategori: "Belanja Barang" },
  { kode: "5.1.02.01",         nama: "Belanja Barang", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01",      nama: "Belanja Barang Pakai Habis", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0001", nama: "Belanja Bahan-Bahan Bangunan dan Konstruksi (Semen, Cat, Besi)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0004", nama: "Belanja Bahan-Bahan Bakar dan Pelumas (BBM, Oli)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0008", nama: "Belanja Bahan-Bahan/Bibit Tanaman", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0011", nama: "Belanja Bahan-Bahan/Bibit Ternak/Bibit Ikan", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0024", nama: "Belanja Alat/Bahan untuk Kegiatan Kantor - Alat Tulis Kantor (Kertas, Pulpen, Tinta, Spidol)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0026", nama: "Belanja Alat/Bahan untuk Kegiatan Kantor - Bahan Cetak dan Penggandaan (Fotokopi, Jilid, Spanduk)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0027", nama: "Belanja Alat/Bahan untuk Kegiatan Kantor - Benda Pos (Perangko, Materai)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0030", nama: "Belanja Alat/Bahan untuk Kegiatan Kantor - Perabot Kantor (Meja, Kursi, Lemari, Rak)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0031", nama: "Belanja Alat/Bahan untuk Kegiatan Kantor - Alat Listrik (Lampu, Baterai, Kabel)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0034", nama: "Belanja Alat/Bahan untuk Kegiatan Kantor - Perlengkapan Pendukung Olahraga", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0037", nama: "Belanja Obat-Obatan (Obat, Vitamin, P3K)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0052", nama: "Belanja Makanan dan Minuman Rapat (Snack, Nasi Kotak, Kopi)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0053", nama: "Belanja Makanan dan Minuman Jamuan Tamu", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0054", nama: "Belanja Penambah Daya Tahan Tubuh (Susu, Suplemen)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0058", nama: "Belanja Makanan dan Minuman Aktivitas Lapangan", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0068", nama: "Belanja Pakaian Siaga (Seragam Olahraga, Pramuka)", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0074", nama: "Belanja Pakaian Adat Daerah", kategori: "Belanja Barang" },
  { kode: "5.1.02.01.01.0076", nama: "Belanja Pakaian Olahraga", kategori: "Belanja Barang" },

  // ─── BELANJA JASA ──────────────────────────────────────────────────────────
  { kode: "5.1.02.02",         nama: "Belanja Jasa", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01",      nama: "Belanja Jasa Kantor", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0003", nama: "Honorarium Narasumber/Pembahas, Moderator, Pembawa Acara, dan Panitia", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0013", nama: "Belanja Jasa Tenaga Pendidikan (Guru Honor, GTT, PTT)", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0027", nama: "Belanja Jasa Tenaga Operator Komputer (Input Dapodik, PIP, Rapor Mutu)", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0028", nama: "Belanja Jasa Tenaga Pelayanan Umum (Ongkos Tukang, Cleaning Service)", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0048", nama: "Belanja Jasa Kontribusi Asosiasi/Iuran Organisasi", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0059", nama: "Belanja Tagihan Telepon", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0060", nama: "Belanja Tagihan Air (PDAM)", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0061", nama: "Belanja Tagihan Listrik (PLN)", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0062", nama: "Belanja Langganan Jurnal/Surat Kabar/Majalah", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0063", nama: "Belanja Kawat/Faksimili/Internet/TV Berlangganan", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.01.0065", nama: "Belanja Penambahan Daya Listrik", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.04",      nama: "Belanja Sewa Peralatan dan Mesin", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.04.0036", nama: "Belanja Sewa Kendaraan Bermotor Penumpang", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.04.0117", nama: "Belanja Sewa Alat Kantor Lainnya (Proyektor, Sound System)", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.04.0118", nama: "Belanja Sewa Mebel", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.04.0132", nama: "Belanja Sewa Peralatan Studio Audio", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.05",      nama: "Belanja Sewa Gedung dan Bangunan", kategori: "Belanja Jasa" },
  { kode: "5.1.02.02.05.0002", nama: "Belanja Sewa Bangunan/Gedung/Aula", kategori: "Belanja Jasa" },

  // ─── BELANJA PEMELIHARAAN ──────────────────────────────────────────────────
  { kode: "5.1.02.03",         nama: "Belanja Pemeliharaan", kategori: "Belanja Pemeliharaan" },
  { kode: "5.1.02.03.02",      nama: "Belanja Pemeliharaan Peralatan dan Mesin", kategori: "Belanja Pemeliharaan" },
  { kode: "5.1.02.03.02.0117", nama: "Belanja Pemeliharaan Alat Kantor dan Rumah Tangga - Alat Kantor Lainnya", kategori: "Belanja Pemeliharaan" },
  { kode: "5.1.02.03.02.0118", nama: "Belanja Pemeliharaan Alat Kantor dan Rumah Tangga - Mebel", kategori: "Belanja Pemeliharaan" },
  { kode: "5.1.02.03.02.0404", nama: "Belanja Pemeliharaan Komputer - Komputer Jaringan", kategori: "Belanja Pemeliharaan" },
  { kode: "5.1.02.03.02.0406", nama: "Belanja Pemeliharaan Komputer - Komputer Unit Lainnya (PC, Laptop, Printer)", kategori: "Belanja Pemeliharaan" },

  // ─── BELANJA PERJALANAN DINAS ──────────────────────────────────────────────
  { kode: "5.1.02.04",         nama: "Belanja Perjalanan Dinas", kategori: "Belanja Perjalanan Dinas" },
  { kode: "5.1.02.04.01",      nama: "Belanja Perjalanan Dinas Dalam Negeri", kategori: "Belanja Perjalanan Dinas" },
  { kode: "5.1.02.04.01.0001", nama: "Belanja Perjalanan Dinas Biasa (Luar Kota)", kategori: "Belanja Perjalanan Dinas" },
  { kode: "5.1.02.04.01.0003", nama: "Belanja Perjalanan Dinas Dalam Kota", kategori: "Belanja Perjalanan Dinas" },

  // ─── BELANJA MODAL ─────────────────────────────────────────────────────────
  { kode: "5.2",               nama: "Belanja Modal", kategori: "Belanja Modal" },
  { kode: "5.2.02",            nama: "Belanja Modal Peralatan dan Mesin", kategori: "Belanja Modal" },
  { kode: "5.2.02.05",         nama: "Belanja Modal Alat Kantor dan Rumah Tangga", kategori: "Belanja Modal" },
  { kode: "5.2.02.05.01",      nama: "Belanja Modal Alat Kantor", kategori: "Belanja Modal" },
  { kode: "5.2.02.05.01.0005", nama: "Belanja Modal Alat Kantor Lainnya", kategori: "Belanja Modal" },
  { kode: "5.2.02.05.02",      nama: "Belanja Modal Alat Rumah Tangga", kategori: "Belanja Modal" },
  { kode: "5.2.02.05.02.0001", nama: "Belanja Modal Meubelair (Meja, Kursi, Lemari > 1 Tahun)", kategori: "Belanja Modal" },
  { kode: "5.2.02.05.02.0004", nama: "Belanja Modal Alat Pendingin (AC, Kipas Angin)", kategori: "Belanja Modal" },
  { kode: "5.2.02.05.02.0006", nama: "Belanja Modal Alat Rumah Tangga Lainnya (Home Use)", kategori: "Belanja Modal" },
  { kode: "5.2.02.07",         nama: "Belanja Modal Alat Kedokteran dan Kesehatan", kategori: "Belanja Modal" },
  { kode: "5.2.02.07.01",      nama: "Belanja Modal Alat Kedokteran", kategori: "Belanja Modal" },
  { kode: "5.2.02.07.01.0029", nama: "Belanja Modal Alat Kedokteran Lainnya (Alat UKS)", kategori: "Belanja Modal" },
  { kode: "5.2.02.08",         nama: "Belanja Modal Alat Laboratorium", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03",      nama: "Belanja Modal Alat Peraga Praktek Sekolah", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03.0001", nama: "Belanja Modal Alat Peraga Praktek Sekolah - Bahasa Indonesia", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03.0002", nama: "Belanja Modal Alat Peraga Praktek Sekolah - Matematika", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03.0003", nama: "Belanja Modal Alat Peraga Praktek Sekolah - IPA Dasar", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03.0004", nama: "Belanja Modal Alat Peraga Praktek Sekolah - IPA Lanjutan", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03.0005", nama: "Belanja Modal Alat Peraga Praktek Sekolah - IPA Menengah", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03.0006", nama: "Belanja Modal Alat Peraga Praktek Sekolah - IPA Atas", kategori: "Belanja Modal" },
  { kode: "5.2.02.08.03.0007", nama: "Belanja Modal Alat Peraga Praktek Sekolah - IPS", kategori: "Belanja Modal" },
  { kode: "5.2.02.10",         nama: "Belanja Modal Komputer", kategori: "Belanja Modal" },
  { kode: "5.2.02.10.01.0002", nama: "Belanja Modal Personal Computer (PC Desktop)", kategori: "Belanja Modal" },
  { kode: "5.2.02.10.01.0003", nama: "Belanja Modal Komputer Unit Lainnya (Laptop, Tablet)", kategori: "Belanja Modal" },
  { kode: "5.2.02.19",         nama: "Belanja Modal Peralatan Olahraga", kategori: "Belanja Modal" },
  { kode: "5.2.02.19.01.0006", nama: "Belanja Modal Peralatan Olahraga Lainnya", kategori: "Belanja Modal" },
  { kode: "5.2.05",            nama: "Belanja Modal Aset Tetap Lainnya", kategori: "Belanja Modal" },
  { kode: "5.2.05.01",         nama: "Belanja Modal Bahan Perpustakaan", kategori: "Belanja Modal" },
  { kode: "5.2.05.01.01",      nama: "Belanja Modal Bahan Perpustakaan Tercetak", kategori: "Belanja Modal" },
  { kode: "5.2.05.01.01.0001", nama: "Belanja Modal Buku Umum (Buku Teks, Referensi, Perpustakaan)", kategori: "Belanja Modal" },
  { kode: "5.2.05.02",         nama: "Belanja Modal Barang Bercorak Kesenian/Kebudayaan/Olahraga", kategori: "Belanja Modal" },
  { kode: "5.2.05.02.01.0001", nama: "Belanja Modal Alat Musik", kategori: "Belanja Modal" },
];