export const refKegiatanArkas2026 = [
  // PROGRAM 02: Standar Isi
  {
    kode_program: "02",
    nama_program: "Standar Isi",
    kode_komponen: "02.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "02.02.01",
    nama_kegiatan: "Penguatan Fungsi Perpustakaan untuk Meningkatkan Minat Baca dan Literasi Peserta Didik",
  },
  {
    kode_program: "02",
    nama_program: "Standar Isi",
    kode_komponen: "02.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "02.03.01",
    nama_kegiatan: "Penyusunan dan Penyesuaian Dokumen Kurikulum Sesuai Kebijakan Satuan Pendidikan",
  },
  {
    kode_program: "02",
    nama_program: "Standar Isi",
    kode_komponen: "02.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "02.03.02",
    nama_kegiatan: "Pengembangan Kurikulum Kompetensi Keahlian yang Relevan dengan Kebutuhan Peserta Didik",
  },
  {
    kode_program: "02",
    nama_program: "Standar Isi",
    kode_komponen: "02.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "02.06.01",
    nama_kegiatan: "Diskusi dan Kolaborasi Pengembangan RPP melalui Komunitas Belajar Pendidik",
  },

  // PROGRAM 03: Standar Proses
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.01",
    nama_komponen: "Penerimaan Peserta Didik Baru",
    kode_kegiatan: "03.01.01",
    nama_kegiatan: "Pelaksanaan Tahapan Pendaftaran Peserta Didik Baru Sesuai Ketentuan yang Berlaku",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.01",
    nama_komponen: "Penerimaan Peserta Didik Baru",
    kode_kegiatan: "03.01.02",
    nama_kegiatan: "Pendataan Ulang Peserta Didik Lama pada Awal Tahun Ajaran",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.01",
    nama_komponen: "Penerimaan Peserta Didik Baru",
    kode_kegiatan: "03.01.03",
    nama_kegiatan: "Pelaksanaan Pengenalan Lingkungan Sekolah yang Edukatif dan Aman",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "03.02.01",
    nama_kegiatan: "Penyelenggaraan Publikasi Sekolah Secara Berkala melalui Media Cetak atau Digital",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "03.02.02",
    nama_kegiatan: "Pengadaan Buku Lembar Kerja Siswa untuk Menunjang Proses Pembelajaran",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "03.02.03",
    nama_kegiatan: "Penyediaan Akses Layanan Perpustakaan Digital atau Platform Literasi Daring",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.01",
    nama_kegiatan: "Penyusunan Silabus serta Perumusan Tujuan Pembelajaran",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.01",
    nama_kegiatan: "Penyusunan Silabus dan Tujuan Pembelajaran oleh Pendidik (PTK)",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.02",
    nama_kegiatan: "Pelaksanaan dan Pengembangan Kegiatan Literasi serta Numerasi Sekolah",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.04",
    nama_kegiatan: "Penerapan Pembelajaran Berbasis Projek termasuk Penguatan Profil Pelajar Pancasila",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.05",
    nama_kegiatan: "Penyelenggaraan Program Perbaikan dan Pengayaan Hasil Belajar Peserta Didik",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.06",
    nama_kegiatan: "Pelaksanaan Kegiatan Ekstrakurikuler Kepramukaan bagi Peserta Didik",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "03.03.06",
    nama_kegiatan: "Pendampingan Kegiatan Kepramukaan oleh Guru dan Tenaga Kependidikan (PTK)",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.07",
    nama_kegiatan: "Pelaksanaan Kegiatan Ekstrakurikuler Selain Kepramukaan",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "03.03.07",
    nama_kegiatan: "Pembinaan dan Pendampingan Ekstrakurikuler Non-Kepramukaan (PTK)",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.08",
    nama_kegiatan: "Pelaksanaan Program Pembinaan Kesiswaan dan Kepemimpinan Peserta Didik",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.10",
    nama_kegiatan: "Pengembangan Program Pencegahan serta Penanganan Kekerasan di Lingkungan Sekolah",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.11",
    nama_kegiatan: "Pelaksanaan Program Pencegahan dan Penanganan Perundungan",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.12",
    nama_kegiatan: "Kegiatan Edukasi dan Pencegahan Penyalahgunaan Narkoba serta Zat Adiktif",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.13",
    nama_kegiatan: "Layanan Konsultasi untuk Peningkatan Mutu Pendidikan oleh Tenaga Profesional",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.14",
    nama_kegiatan: "Pelaksanaan Pesantren Kilat dan Kegiatan Keagamaan Sejenis",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.15",
    nama_kegiatan: "Kegiatan Pelibatan Orang Tua dan Keluarga dalam Proses Pembelajaran",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.16",
    nama_kegiatan: "Penyusunan Pembagian Tugas Guru serta Penjadwalan Kegiatan Belajar",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.17",
    nama_kegiatan: "Dukungan Pembiayaan Partisipasi Kegiatan Berbagi Praktik Baik Pendidikan",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.18",
    nama_kegiatan: "Penguatan Pemanfaatan TIK untuk Mendukung Kegiatan Pembelajaran",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.19",
    nama_kegiatan: "Pelaksanaan Berbagai Kegiatan Lomba Akademik dan Nonakademik",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.20",
    nama_kegiatan: "Pelaksanaan Berbagai Program Sekolah Lain yang Mendukung Kegiatan Pembelajaran",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.21",
    nama_kegiatan: "Perayaan Hari Besar Keagamaan, Nasional, dan Daerah di Lingkungan Sekolah",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "03.03.22",
    nama_kegiatan: "Penerapan Pembelajaran Aktif, Kreatif, Efektif, dan Menyenangkan",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "03.04.01",
    nama_kegiatan: "Pelaksanaan Supervisi Pembelajaran Seluruh Guru dan Mata Pelajaran",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "03.04.02",
    nama_kegiatan: "Evaluasi Pelaksanaan Kegiatan Ekstrakurikuler Sekolah",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "03.05.01",
    nama_kegiatan: "Kegiatan Koordinasi dan Pelaporan untuk Mendukung Program Prioritas Pemerintah",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "03.05.02",
    nama_kegiatan: "Penyelenggaraan UKS serta Penyediaan Sarana Pendukung Kesehatan Sekolah",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.10",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "03.10.01",
    nama_kegiatan: "Pengembangan Kerja Sama dengan Dunia Industri untuk Peningkatan Kompetensi Peserta Didik",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.10",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "03.10.02",
    nama_kegiatan: "Pengembangan Ruang Lingkup Skema Sertifikasi Kompetensi",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.11",
    nama_komponen: "Penyerapan Lulusan",
    kode_kegiatan: "03.11.01",
    nama_kegiatan: "Pelaksanaan Pembelajaran yang Berkaitan dengan Budaya Kerja",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.11",
    nama_komponen: "Penyerapan Lulusan",
    kode_kegiatan: "03.11.02",
    nama_kegiatan: "Penyelenggaraan Bursa Kerja Khusus bagi Lulusan SMK atau SMALB",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.11",
    nama_komponen: "Penyerapan Lulusan",
    kode_kegiatan: "03.11.03",
    nama_kegiatan: "Pelaksanaan Pemantauan Kebekerjaan Lulusan melalui Tracer Study",
  },
  {
    kode_program: "03",
    nama_program: "Standar Proses",
    kode_komponen: "03.11",
    nama_komponen: "Penyerapan Lulusan",
    kode_kegiatan: "03.11.04",
    nama_kegiatan: "Penyelenggaraan Pendidikan Kejuruan bagi Peserta Didik SMK atau SMALB",
  },

  // PROGRAM 04: Standar Pendidik dan Tenaga Kependidikan
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.01",
    nama_kegiatan: "Pelaksanaan Kegiatan Komunitas Belajar di Satuan Pendidikan",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.02",
    nama_kegiatan: "Kegiatan Komunitas Belajar Antar Sekolah seperti KKG, MGMP, atau MKKS",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.03",
    nama_kegiatan: "Pengembangan Diri Guru dan Tenaga Kependidikan di Luar Platform PMM",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.04",
    nama_kegiatan: "Pengembangan Diri Guru dan Tenaga Kependidikan melalui Platform Merdeka Mengajar",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.05",
    nama_kegiatan: "Kegiatan Peningkatan Kompetensi Guru Sesuai Kebutuhan Sekolah",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.06",
    nama_kegiatan: "Peningkatan Kompetensi Kepala Sekolah dalam Pengelolaan Satuan Pendidikan",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.07",
    nama_kegiatan: "Pembinaan Kompetensi Tenaga Pelaksana Sekolah seperti TU, Laboran, dan Pustakawan",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.08",
    nama_kegiatan: "Fasilitasi Keikutsertaan Guru dalam Berbagai Kegiatan Prestasi dan Penghargaan",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.09",
    nama_kegiatan: "Pelaksanaan Kegiatan Magang Guru di Sekolah Lain",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.11",
    nama_kegiatan: "Peningkatan Kompetensi Guru untuk Pelibatan Orang Tua dan Masyarakat",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.12",
    nama_kegiatan: "Peningkatan Kompetensi Guru dalam Menciptakan Lingkungan Belajar yang Aman dan Nyaman",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.13",
    nama_kegiatan: "Peningkatan Kompetensi Guru untuk Penguatan Kemampuan Numerasi",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.14",
    nama_kegiatan: "Peningkatan Kompetensi Guru untuk Penguatan Kemampuan Literasi",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.22",
    nama_kegiatan: "Peningkatan Kompetensi Guru dalam Memahami Konten Pembelajaran dan Strategi Pengajaran",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.23",
    nama_kegiatan: "Peningkatan Kompetensi Guru dalam Memahami dan Menerapkan Kurikulum",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.24",
    nama_kegiatan: "Pengembangan Kompetensi Guru melalui Pembiasaan Refleksi Diri",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.25",
    nama_kegiatan: "Peningkatan Kompetensi Guru untuk Pembelajaran yang Berorientasi pada Peserta Didik",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.26",
    nama_kegiatan: "Penguatan Kompetensi Guru terkait Kematangan Moral, Emosional, dan Spiritual Sesuai Kode Etik",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.27",
    nama_kegiatan: "Peningkatan Kompetensi Guru dalam Asesmen, Umpan Balik, dan Pelaporan yang Berpusat pada Peserta Didik",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.31",
    nama_kegiatan: "Penguatan Pemahaman Profil Pelajar Pancasila pada Aspek Keimanan dan Akhlak Mulia",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.32",
    nama_kegiatan: "Peningkatan Pemahaman Profil Pelajar Pancasila pada Nilai Gotong Royong",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.33",
    nama_kegiatan: "Penguatan Pemahaman Profil Pelajar Pancasila pada Aspek Kreativitas",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.34",
    nama_kegiatan: "Peningkatan Pemahaman Profil Pelajar Pancasila pada Kemampuan Bernalar Kritis",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.35",
    nama_kegiatan: "Penguatan Pemahaman Profil Pelajar Pancasila pada Nilai Kebinekaan Global",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.36",
    nama_kegiatan: "Peningkatan Pemahaman Profil Pelajar Pancasila pada Aspek Kemandirian",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.41",
    nama_kegiatan: "Peningkatan Pemahaman Guru terkait Perundungan, Kekerasan, dan Kekerasan Seksual",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.42",
    nama_kegiatan: "Penguatan Kompetensi Guru dalam Penerapan Disiplin Positif tanpa Kekerasan Fisik",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.43",
    nama_kegiatan: "Peningkatan Pemahaman Guru mengenai Bahaya Narkoba, Rokok, Miras, dan HIV AIDS",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.44",
    nama_kegiatan: "Penguatan Pemahaman Guru tentang Toleransi, Kesetaraan, dan Moderasi Beragama",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.45",
    nama_kegiatan: "Peningkatan Pemahaman Guru terhadap Nilai Kebangsaan dan Komitmen Bernegara",
  },
  {
    kode_program: "04",
    nama_program: "Standar Pendidik dan Tenaga Kependidikan",
    kode_komponen: "04.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "04.06.46",
    nama_kegiatan: "Penguatan Kompetensi Guru terkait Sikap Inklusif dan Kesetaraan Gender",
  },

  // PROGRAM 05: Standar Sarana dan Prasarana
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "05.02.01",
    nama_kegiatan: "Pemeliharaan Koleksi Buku dan Bahan Pustaka Perpustakaan Sekolah",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "05.02.02",
    nama_kegiatan: "Pengadaan Buku dan Koleksi Perpustakaan Selain Buku Teks Utama",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "05.02.03",
    nama_kegiatan: "Pengadaan Buku Teks Utama atau Pendamping bagi Peserta Didik",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "05.02.04",
    nama_kegiatan: "Pengadaan Buku Teks Utama atau Pendamping bagi Guru",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.02",
    nama_komponen: "Pengembangan Perpustakaan",
    kode_kegiatan: "05.02.05",
    nama_kegiatan: "Pengadaan Buku Pengayaan dan Bahan Referensi Perpustakaan",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "05.05.01",
    nama_kegiatan: "Penyediaan atau Pembuatan Media Pembelajaran untuk Mendukung Kegiatan Belajar",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "05.05.02",
    nama_kegiatan: "Pengembangan Program Sekolah Sehat, Aman, Ramah Anak, Inklusif, dan Berwawasan Lingkungan",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.01",
    nama_kegiatan: "Pemeliharaan Lahan, Bangunan, dan Ruang Sekolah",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.02",
    nama_kegiatan: "Pengadaan Peralatan Sekolah di Luar Perangkat Multimedia Pembelajaran",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.03",
    nama_kegiatan: "Pemeliharaan Peralatan Sekolah untuk Menunjang Operasional",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.04",
    nama_kegiatan: "Pengadaan Perlengkapan Sekolah Selain Alat Multimedia Pembelajaran",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.05",
    nama_kegiatan: "Pemeliharaan Perlengkapan Sekolah Secara Berkala",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.06",
    nama_kegiatan: "Penyediaan Fasilitas Akses bagi Peserta Didik Penyandang Disabilitas",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.07",
    nama_kegiatan: "Pengadaan Peralatan Pendukung Pembelajaran bagi Peserta Didik Penyandang Disabilitas",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.08",
    nama_kegiatan: "Penyediaan Sarana dan Perlengkapan untuk Mendukung Layanan Pendidikan Inklusif",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.09",
    nama_kegiatan: "Pengadaan Perlengkapan Daya dan Jasa Sekolah seperti Listrik, Air, dan Internet",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.10",
    nama_kegiatan: "Pemeliharaan Instalasi dan Layanan Daya serta Jasa Sekolah",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.11",
    nama_kegiatan: "Pengadaan Seragam Inventaris bagi Peserta Didik, Pendidik, dan Tenaga Kependidikan",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.08",
    nama_komponen: "Pemeliharaan Sarana dan Prasarana",
    kode_kegiatan: "05.08.12",
    nama_kegiatan: "Pelaksanaan Tindakan Tanggap Darurat Akibat Bencana pada Lingkungan Sekolah",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.09",
    nama_komponen: "Alat Multimedia Pembelajaran",
    kode_kegiatan: "05.09.01",
    nama_kegiatan: "Pengadaan Komputer Desktop atau Workstation untuk Pembelajaran dan Administrasi",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.09",
    nama_komponen: "Alat Multimedia Pembelajaran",
    kode_kegiatan: "05.09.02",
    nama_kegiatan: "Pengadaan Laptop atau Notebook untuk Kegiatan Pembelajaran dan Administrasi",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.09",
    nama_komponen: "Alat Multimedia Pembelajaran",
    kode_kegiatan: "05.09.04",
    nama_kegiatan: "Pengadaan Printer, Scanner, atau Perangkat Cetak dan Pindai Lainnya",
  },
  {
    kode_program: "05",
    nama_program: "Standar Sarana dan Prasarana",
    kode_komponen: "05.09",
    nama_komponen: "Alat Multimedia Pembelajaran",
    kode_kegiatan: "05.09.05",
    nama_kegiatan: "Pengadaan Proyektor serta Layar LCD atau LED untuk Kegiatan Pembelajaran",
  },

  // PROGRAM 06: Standar Pengelolaan
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.01",
    nama_kegiatan: "Penyusunan Perencanaan Program Satuan Pendidikan seperti Visi, Misi, dan RKAS",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.02",
    nama_kegiatan: "Pengembangan serta Pelaksanaan Program Kerja Kepala Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.03",
    nama_kegiatan: "Pelaksanaan Pendataan dan Pemutakhiran Data Dapodik",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.04",
    nama_kegiatan: "Pelaksanaan Monitoring dan Evaluasi Program serta Kegiatan Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.05",
    nama_kegiatan: "Pelaksanaan Supervisi Administrasi Tata Usaha Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.06",
    nama_kegiatan: "Penyediaan Konsumsi untuk Rapat Kedinasan dan Tamu Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.07",
    nama_kegiatan: "Pengadaan Bahan Pembelajaran dan Praktik termasuk Kebutuhan Bengkel Kejuruan",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.08",
    nama_kegiatan: "Pembelian Bahan Habis Pakai untuk Pembelajaran dan Administrasi Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.09",
    nama_kegiatan: "Pengadaan Bahan dan Alat Penunjang Kebersihan serta Sanitasi Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.10",
    nama_kegiatan: "Pengadaan Bahan Habis Pakai dan Suku Cadang untuk Kegiatan Rumah Tangga Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.11",
    nama_kegiatan: "Pengelolaan Operasional Rutin Sekolah dalam Pembelajaran Jarak Jauh",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.12",
    nama_kegiatan: "Pengembangan dan Pemeliharaan Website serta Media Sosial Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.13",
    nama_kegiatan: "Pengembangan Sistem Informasi untuk Mendukung Manajemen Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "06.05.14",
    nama_kegiatan: "Pelaksanaan Perjalanan Dinas untuk Koordinasi dan Pelaporan ke Dinas Pendidikan",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "06.06.01",
    nama_kegiatan: "Kerja Sama dengan Sekolah Bertaraf Internasional untuk Peningkatan Kompetensi Guru",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.01",
    nama_kegiatan: "Pembayaran Biaya Listrik Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.02",
    nama_kegiatan: "Penambahan Kapasitas Daya Listrik Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.03",
    nama_kegiatan: "Pembayaran Biaya Langganan Air Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.04",
    nama_kegiatan: "Pembayaran Biaya Layanan Telepon untuk Kebutuhan Operasional Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.05",
    nama_kegiatan: "Pembayaran Biaya Langganan Internet Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.06",
    nama_kegiatan: "Penambahan Kapasitas Layanan Internet untuk Mendukung Pembelajaran",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.07",
    nama_kegiatan: "Pengadaan Bahan Bakar Minyak atau Gas untuk Keperluan Pembelajaran dan Rumah Tangga Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.08",
    nama_kegiatan: "Pembayaran Retribusi Keamanan dan Pengelolaan Sampah Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.09",
    nama_kegiatan: "Pembayaran Langganan Koran dan Majalah sebagai Sumber Informasi Sekolah",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.10",
    nama_kegiatan: "Sewa Genset untuk Mendukung Ketersediaan Daya Listrik",
  },
  {
    kode_program: "06",
    nama_program: "Standar Pengelolaan",
    kode_komponen: "06.07",
    nama_komponen: "Langganan Daya dan Jasa",
    kode_kegiatan: "06.07.12",
    nama_kegiatan: "Pembayaran Sewa Rumah, Gedung, Gudang, atau Lahan Penunjang Sekolah",
  },

  // PROGRAM 07: Standar Pembiayaan
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "07.05.01",
    nama_kegiatan: "Pembayaran Bea Materai dan Biaya Administrasi Perbankan",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "07.05.02",
    nama_kegiatan: "Penggandaan Laporan, Dokumen, dan Surat-Menyurat Sekolah",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "07.05.03",
    nama_kegiatan: "Penyelenggaraan Sosialisasi dan Pelaporan Program serta Pengelolaan Keuangan",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "07.05.04",
    nama_kegiatan: "Kegiatan Inventarisasi dan Pendokumentasian Nilai Aset Sarana Prasarana Sekolah",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "07.05.05",
    nama_kegiatan: "Pengelolaan dan Pelaporan Pendanaan dari Pihak Ketiga atau Mitra",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.05",
    nama_komponen: "Administrasi Kegiatan Sekolah",
    kode_kegiatan: "07.05.06",
    nama_kegiatan: "Perjalanan Dinas Pengambilan Dana BOS di Bank bagi Sekolah Terpencil",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.10",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "07.10.01",
    nama_kegiatan: "Pelaksanaan Kegiatan Pemagangan Guru atau Peserta Didik di Dunia Industri",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.10",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "07.10.02",
    nama_kegiatan: "Pelaksanaan Praktik Kerja Industri atau Lapangan bagi Peserta Didik",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.10",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "07.10.03",
    nama_kegiatan: "Penyelenggaraan Uji Kompetensi Kemampuan Bahasa Asing",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.10",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "07.10.04",
    nama_kegiatan: "Pelaksanaan Kegiatan Lembaga Sertifikasi Profesi Pihak Pertama",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.10",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "07.10.05",
    nama_kegiatan: "Penyelenggaraan Uji Kompetensi dan Sertifikasi Keahlian Peserta Didik",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.11",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "07.11.01",
    nama_kegiatan: "Pengembangan Pembelajaran Berbasis Teaching Factory",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.11",
    nama_komponen: "Peningkatan Kompetensi Keahlian",
    kode_kegiatan: "07.11.02",
    nama_kegiatan: "Penyelenggaraan Kegiatan Sertifikasi Kompetensi Peserta Didik",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.12",
    nama_komponen: "Pembayaran Honor",
    kode_kegiatan: "07.12.01",
    nama_kegiatan: "Pembayaran Honor Guru atau Pendidik",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.12",
    nama_komponen: "Pembayaran Honor",
    kode_kegiatan: "07.12.02",
    nama_kegiatan: "Pembayaran Honor Tenaga Kependidikan Selain Pendidik",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.12",
    nama_komponen: "Pembayaran Honor",
    kode_kegiatan: "07.12.03",
    nama_kegiatan: "Pembayaran Honor Tenaga Administrasi Sekolah",
  },
  {
    kode_program: "07",
    nama_program: "Standar Pembiayaan",
    kode_komponen: "07.12",
    nama_komponen: "Pembayaran Honor",
    kode_kegiatan: "07.12.04",
    nama_kegiatan: "Pembayaran Honor Tenaga Penunjang atau Pelaksana Kegiatan",
  },

  // PROGRAM 08: Standar Penilaian
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "08.03.01",
    nama_kegiatan: "Seleksi Peserta Didik untuk Program Kelas Bilingual",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.03",
    nama_komponen: "Pelaksanaan Pembelajaran dan Ekstrakurikuler",
    kode_kegiatan: "08.03.02",
    nama_kegiatan: "Seleksi Peserta Didik untuk Program Kelas Akselerasi",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.01",
    nama_kegiatan: "Persiapan, Simulasi, dan Pelaksanaan Asesmen Nasional",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.02",
    nama_kegiatan: "Pelaksanaan Asesmen Awal untuk Mengidentifikasi Kemampuan Peserta Didik",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.03",
    nama_kegiatan: "Penyusunan Kisi-Kisi serta Perancangan Soal Penilaian Formatif",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.04",
    nama_kegiatan: "Pelaksanaan Penilaian Formatif seperti Ulangan Harian",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.05",
    nama_kegiatan: "Penyusunan Kisi-Kisi dan Soal Penilaian Sumatif Tengah dan Akhir Semester",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.06",
    nama_kegiatan: "Pelaksanaan Penilaian Sumatif Semester dan Kenaikan Kelas",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.07",
    nama_kegiatan: "Penyusunan Kisi-Kisi dan Soal Asesmen Akhir Sekolah",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.08",
    nama_kegiatan: "Persiapan dan Pelaksanaan Asesmen Sekolah termasuk Berbasis Komputer",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.09",
    nama_kegiatan: "Penyusunan Kriteria dan Ketentuan Kenaikan Kelas Peserta Didik",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.10",
    nama_kegiatan: "Penyusunan Kompetensi Ketuntasan Minimal Mata Pelajaran",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.04",
    nama_komponen: "Asesmen dan Evaluasi Pembelajaran",
    kode_kegiatan: "08.04.11",
    nama_kegiatan: "Pengembangan Perangkat Asesmen untuk Pembelajaran Kejuruan",
  },
  {
    kode_program: "08",
    nama_program: "Standar Penilaian",
    kode_komponen: "08.06",
    nama_komponen: "Pengembangan Profesi Guru dan Tendik",
    kode_kegiatan: "08.06.01",
    nama_kegiatan: "Fasilitasi Pengembangan Kompetensi Guru melalui Pelatihan dan Diseminasi Program Pendidikan",
  },
] as const;